const fileTypeMappings: Record<string, string> = {
	jpg: 'image/jpeg',
	jpeg: 'image/jpeg',
	png: 'image/png',
	gif: 'image/gif',
	bmp: 'image/bmp',
	svg: 'image/svg+xml',
	webp: 'image/webp',
	ico: 'image/vnd.microsoft.icon',
	css: 'text/css',
	html: 'text/html',
	xhtml: 'application/xhtml+xml',
	htm: 'text/html',
	js: 'application/javascript',
	json: 'application/json',
	xml: 'application/xml',
	pdf: 'application/pdf',
	txt: 'text/plain',
	csv: 'text/csv',
	tsv: 'text/tab-separated-values',
	md: 'text/markdown',
	mp4: 'video/mp4',
	webm: 'video/webm',
	ogg: 'audio/ogg',
	mp3: 'audio/mpeg',
	wav: 'audio/wav',
	flac: 'audio/flac',
	zip: 'application/zip',
	tar: 'application/x-tar',
	gz: 'application/gzip',
	rar: 'application/vnd.rar',
	// eslint-disable-next-line @typescript-eslint/naming-convention
	'7z': 'application/x-7z-compressed',
	epub: 'application/epub+zip',
	mobi: 'application/x-mobipocket-ebook',
	azw: 'application/vnd.amazon.ebook',
	ncx: 'application/x-dtbncx+xml',
};

export default fileTypeMappings;
